language: python

python:
  - 3.8

install:
  - cd swe1app
  - pip install -r requirements.txt
  - cd ..

before_script:
  - cd swe1app
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - cd ..

script:
  - black --check .
  - flake8 .
  - cd swe1app
  - coverage run --source=swe1app,polls manage.py test
  - cd ..

after_script:
  - coveralls
