language: python

python:
  - 3.8

install:
  - cd swe1app
  - pip install -r requirements.txt
  - cd ..

before_script:
  - cd swe1app
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - cd ..

script:
  - black .
  - flake8 .
  - cd swe1app
  - coverage run --source=swe1app,polls manage.py test
  - cd ..

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "swe1app"
  env: "swe1app-env"
  bucket_name: $AWS_BUCKET
  on:
    repo: agoluoglu/swe1-app
    branch: main
